/**
*	This file contains the implementation of an hash translator.
*	Given a hash generated by spooky_hash32.go translates it into the address of a bucket
*   bucket_id = hash % buffer_pool_size
*
**/
package store

const BUFFER_POOL_SIZE uint32 = 3000

type AddressBinder struct {
	bucketAddress uint32
}

func NewAddressBinder() *AddressBinder {
	return &AddressBinder{}
}

/**
*	@brief calculate the bucket address
*   @param hash value calculated by the hash function
*   @return bucket address
*   if the hash is for example 1177965712 the corresponding bucket
*   address is 712
 */
func (a *AddressBinder) TranslateHash(hash uint32) uint32 {
	a.bucketAddress = hash % BUFFER_POOL_SIZE
	return a.bucketAddress
}
